create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(500), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
create sequence hibernate_sequence start 1 increment 1
create table image (id int8 not null, content_type varchar(255), original_name varchar(255), bytes oid, is_previewed_image boolean, name varchar(255), size int8, product_id int8, primary key (id))
create table products (id int8 not null, city varchar(255), date date, description text, preview_image_id int8, price int4, title varchar(255), user_id int8, primary key (id))
create table user_role (user_id int8 not null, roles varchar(255))
create table users (id int8 generated by default as identity, active boolean, date_of_created timestamp, email varchar(255), name varchar(255), password varchar(1000), phone_number varchar(255), image_id int8, primary key (id))
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table if exists image add constraint FKo6o5cjl2h3n5g87df5afdt17f foreign key (product_id) references products
alter table if exists products add constraint FKdb050tk37qryv15hd932626th foreign key (user_id) references users
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users
alter table if exists users add constraint FKlqj25c28swu46s4jbudd7hore foreign key (image_id) references image
