<!DOCTYPE html>
<html>
<head>

</head>
<body>
<h1>Create a new order</h1><hr>
<form action="/product/create" method="post">
    Order name: <input type="text" name="title"/><br><br>
    Description: <input type="text" name="description"/><br><br>
    Price: <input type="number" name="price"/><br><br>
    Author: <input type="text" name="author"/><br><br>
    City: <input type="text" name="city"/><br><br>
    <input type="submit" value="Create"/>
</form>
</body>

</html>

